"""update in book table

Revision ID: 31d950395841
Revises: ad868fe02b49
Create Date: 2025-04-24 11:20:02.649292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d950395841'
down_revision: Union[str, None] = 'ad868fe02b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.String(), nullable=True))
    op.drop_column('books', 'published_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
